version: '2'
services:
    backend:
        container_name: testtech
        build:
            context: ./testTech
            dockerfile: Dockerfile
        image: testtech:latest
        ports:
            - 8025:8025
        networks:
            - spring-cloud-network
    mongodb:
        image: mongo:5.0
        ports:
            - 27017:27017
        volumes:
            - ~/apps/mongo:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=test
            - MONGO_INITDB_ROOT_PASSWORD=test123
            - MONGO_INITDB_DATABASE=testDB

        networks:
            - spring-cloud-network
    # frontend:
    #     container_name: product-server
    #     build:
    #         context: docker-product-server
    #         dockerfile: Dockerfile
    #     image: product-server:latest
    #     ports:
    #         - 19999:9999
    #     networks:
    #         - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge