version: '2'
services:
    backend:
        depends_on:
            - mongodb
        container_name: testtech
        build:
            context: ./testTech
            dockerfile: Dockerfile
        image: testtech:latest
        ports:
            - 8025:8025
        links:
            - mongodb
    mongodb:
        image: mongo:5.0
        ports:
            - 27017:27017
        volumes:
            - ~/apps/mongo:/data/db
        hostname: mongo
    # frontend:
    #     container_name: product-server
    #     build:
    #         context: docker-product-server
    #         dockerfile: Dockerfile
    #     image: product-server:latest
    #     ports:
    #         - 19999:9999
    #     networks:
    #         - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge